name: "More Samples for Diversity"
slug: "diversity_samples"
admins:
  - "sycophancy-1"

model_configs:
  # - 'deepseek/deepseek_v32_think'
  # - 'gemini/gemini-3-flash'
  # - 'gemini/gemini-31-pro'
  # - 'openai/gpt-54'
  # - 'stepfun/3.5-flash'
  - 'glm/glm-5'
  # - 'xai/grok-41-fast-reasoning'
  # - 'moonshot/k25'
  # - 'qwen/qwen35_397b_a17b_high'
  # - "openai/oss-120b"
