n_problems: 400
overlap: 0
judge_file: "configs/judges/verification.json"
competition_weight:
 bmosl: 1
 bulgaria: 1
 india: 1
 india_prep: 1
 usatst: 1
 rmm: 1
 bmo: 1
 philippines: 1
 chinatst: 1
 israel: 1
 korea: 1
 turkey: 1
 china: 1
 egmo: 1
 iran: 1
 matharena: 1
 allrussian: 1
 izho: 1
 imosl: 1
 pan-african: 1
 polish: 1
 serbia: 1
 romania: 1
 vietnam: 1
 elmosl: 1
