model: x-ai/grok-4.1-fast
api: openrouter
max_tokens: 130000
read_cost: 0.2
write_cost: 0.5
human_readable_id: Grok 4 Fast (Reasoning)
concurrent_requests: 64
temperature: null
top_p: null
date: "2025-11-17"
