prompt: |
  Your task is to write a proof solution to the following problem, focusing on accuracy, thoroughness, and clarity. You should make sure that your proof contains as little extra comments as possible, and is as concise as possible so long as the proof is correct. When you write your proof, follow these guidelines:

  - You are creating a proof, not a proof outline. Each step should be carefully explained and documented. If not properly explained, the judge will assume that you cannot explain it, and therefore decrease your grade.
  - You can use general theorems and lemmas, but only if they are well-known. As a rule of thumb: if the result has a name and is famous enough to have a Wikipedia page or something similar to describe it, it is allowed. Any result from papers that would not be taught in high-school or low-level bachelor courses in mathematics should not be used.
  - Do not skip computation steps in your proof. Clearly explain what transformations were done and why they are allowed in each step of a calculation.
  - Your proof should be self-contained.
  - Make sure the proof is as concise as possible while still being correct. Avoid additional explanations or comments that are not strictly necessary for the correctness of the proof.
  - Put your final answer within \\boxed{{}}.

  {problem}
prompt_gold: |
  Your task is to write a proof solution to the following problem, focusing on accuracy, thoroughness, and clarity. You should make sure that your proof contains as little extra comments as possible, and is as concise as possible so long as the proof is correct. When you write your proof, follow these guidelines:

  - You are creating a proof, not a proof outline. Each step should be carefully explained and documented. If not properly explained, the judge will assume that you cannot explain it, and therefore decrease your grade.
  - You can use general theorems and lemmas, but only if they are well-known. As a rule of thumb: if the result has a name and is famous enough to have a Wikipedia page or something similar to describe it, it is allowed. Any result from papers that would not be taught in high-school or low-level bachelor courses in mathematics should not be used.
  - Do not skip computation steps in your proof. Clearly explain what transformations were done and why they are allowed in each step of a calculation.
  - Your proof should be self-contained.
  - Make sure the proof is as concise as possible while still being correct. Avoid additional explanations or comments that are not strictly necessary for the correctness of the proof.
  - Put your final answer within \\boxed{{}}.

  {problem}
n_attempts: 10
n_samples: -1
n_solutions: 1
problem_regexes:
  - .*
allow_shuffle: true
overwrite: false
