prompt: |
  Your task is to write a proof solution to the following problem. You will be required to solve the problem using a specific solving technique. When you write your proof, follow these guidelines:

  - You are creating a proof, not a proof outline. Each step should be carefully explained and documented. If not properly explained, the judge will assume that you cannot explain it, and therefore decrease your grade.
  - You can use general theorems and lemmas, but only if they are well-known. As a rule of thumb: if the result has a name and is famous enough to have a Wikipedia page or something similar to describe it, it is allowed. Any result from papers that would not be taught in high-school or low-level bachelor courses in mathematics should not be used.
  - Do not skip computation steps in your proof. Clearly explain what transformations were done and why they are allowed in each step of a calculation.
  - Your proof should be self-contained.
  - Your proof should make use of the specified technique. You will not receive any credit if you fail to use the specified technique.
  - If you cannot complete the proof with the given technique, do not make up an alternative method or an alternative meaning for the technique.
  - If you are not sure about a specific step, or do not know how to prove an intermediate result, clearly state this. It is much preferable to indicate your uncertainty rather than making incorrect statements or claims.
  - Put your final answer within \\boxed{{}}.

  {problem}

  Solve the problem by using the following method, technique, or outline: {technique}
prompt_gold: |
  Your task is to write a proof solution to the following problem. You will be required to solve the problem using a specific solving technique. When you write your proof, follow these guidelines:

  - You are creating a proof, not a proof outline. Each step should be carefully explained and documented. If not properly explained, the judge will assume that you cannot explain it, and therefore decrease your grade.
  - You can use general theorems and lemmas, but only if they are well-known. As a rule of thumb: if the result has a name and is famous enough to have a Wikipedia page or something similar to describe it, it is allowed. Any result from papers that would not be taught in high-school or low-level bachelor courses in mathematics should not be used.
  - Do not skip computation steps in your proof. Clearly explain what transformations were done and why they are allowed in each step of a calculation.
  - Your proof should be self-contained.
  - Your proof should make use of the specified technique. You will not receive any credit if you fail to use the specified technique.
  - If you cannot complete the proof with the given technique, do not make up an alternative method or an alternative meaning for the technique.
  - If you are not sure about a specific step, or do not know how to prove an intermediate result, clearly state this. It is much preferable to indicate your uncertainty rather than making incorrect statements or claims.
  - Put your final answer within \\boxed{{}}.

  {problem}

  Solve the problem by using the following method, technique, or outline: {technique}
n_attempts: 10
n_samples: -1
n_solutions: 1
problem_regexes:
  - .*
allow_shuffle: true
overwrite: false
