model: stepfun/step-3.5-flash
api: openrouter
max_tokens: 250000
read_cost: 0.1
write_cost: 0.3
human_readable_id: Step 3.5 Flash
batch_processing: false
openai_responses: false
date: "2026-02-02"
temperature: 1
concurrent_requests: 64
top_p: 1
