model: qwen/qwen3.5-397b-a17b
api: openrouter
max_tokens: 192000
temperature: 0.6
top_p: 0.95
concurrent_requests: 64
read_cost: 0.4
write_cost: 2.4
human_readable_id: Qwen3.5-397B-A17B
date: "2025-04-29"
