model: deepseek/deepseek-v3.2
api: openrouter
concurrent_requests: 72
max_tokens: 128000
temperature: 1.0
top_p: 0.95
read_cost: 0.25
write_cost: 0.4
reasoning_effort: high
human_readable_id: DeepSeek-v3.2 (Think)
date: "2025-12-01"
